export interface CountryOption {
  country: string;
  code: string;
  currencyCode: string;
  currencyName: string;
}

export const countryData : CountryOption[] = [
  { "country": "Afghanistan", "code": "AF", "currencyCode": "AFN", "currencyName": "Afghan Afghani" },
  { "country": "Albania", "code": "AL", "currencyCode": "ALL", "currencyName": "Albanian Lek" },
  { "country": "Algeria", "code": "DZ", "currencyCode": "DZD", "currencyName": "Algerian Dinar" },
  { "country": "Andorra", "code": "AD", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Angola", "code": "AO", "currencyCode": "AOA", "currencyName": "Angolan Kwanza" },
  { "country": "Antigua and Barbuda", "code": "AG", "currencyCode": "XCD", "currencyName": "East Caribbean Dollar" },
  { "country": "Argentina", "code": "AR", "currencyCode": "ARS", "currencyName": "Argentine Peso" },
  { "country": "Armenia", "code": "AM", "currencyCode": "AMD", "currencyName": "Armenian Dram" },
  { "country": "Australia", "code": "AU", "currencyCode": "AUD", "currencyName": "Australian Dollar" },
  { "country": "Austria", "code": "AT", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Azerbaijan", "code": "AZ", "currencyCode": "AZN", "currencyName": "Azerbaijani Manat" },
  { "country": "Bahamas", "code": "BS", "currencyCode": "BSD", "currencyName": "Bahamian Dollar" },
  { "country": "Bahrain", "code": "BH", "currencyCode": "BHD", "currencyName": "Bahraini Dinar" },
  { "country": "Bangladesh", "code": "BD", "currencyCode": "BDT", "currencyName": "Bangladeshi Taka" },
  { "country": "Barbados", "code": "BB", "currencyCode": "BBD", "currencyName": "Barbadian Dollar" },
  { "country": "Belarus", "code": "BY", "currencyCode": "BYN", "currencyName": "Belarusian Ruble" },
  { "country": "Belgium", "code": "BE", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Belize", "code": "BZ", "currencyCode": "BZD", "currencyName": "Belize Dollar" },
  { "country": "Benin", "code": "BJ", "currencyCode": "XOF", "currencyName": "West African CFA Franc" },
  { "country": "Bhutan", "code": "BT", "currencyCode": "BTN", "currencyName": "Bhutanese Ngultrum" },
  { "country": "Bolivia", "code": "BO", "currencyCode": "BOB", "currencyName": "Bolivian Boliviano" },
  { "country": "Bosnia and Herzegovina", "code": "BA", "currencyCode": "BAM", "currencyName": "Bosnia and Herzegovina Convertible Mark" },
  { "country": "Botswana", "code": "BW", "currencyCode": "BWP", "currencyName": "Botswana Pula" },
  { "country": "Brazil", "code": "BR", "currencyCode": "BRL", "currencyName": "Brazilian Real" },
  { "country": "Brunei", "code": "BN", "currencyCode": "BND", "currencyName": "Brunei Dollar" },
  { "country": "Bulgaria", "code": "BG", "currencyCode": "BGN", "currencyName": "Bulgarian Lev" },
  { "country": "Burkina Faso", "code": "BF", "currencyCode": "XOF", "currencyName": "West African CFA Franc" },
  { "country": "Burundi", "code": "BI", "currencyCode": "BIF", "currencyName": "Burundian Franc" },
  { "country": "Cabo Verde", "code": "CV", "currencyCode": "CVE", "currencyName": "Cape Verdean Escudo" },
  { "country": "Cambodia", "code": "KH", "currencyCode": "KHR", "currencyName": "Cambodian Riel" },
  { "country": "Cameroon", "code": "CM", "currencyCode": "XAF", "currencyName": "Central African CFA Franc" },
  { "country": "Canada", "code": "CA", "currencyCode": "CAD", "currencyName": "Canadian Dollar" },
  { "country": "Central African Republic", "code": "CF", "currencyCode": "XAF", "currencyName": "Central African CFA Franc" },
  { "country": "Chad", "code": "TD", "currencyCode": "XAF", "currencyName": "Central African CFA Franc" },
  { "country": "Chile", "code": "CL", "currencyCode": "CLP", "currencyName": "Chilean Peso" },
  { "country": "China", "code": "CN", "currencyCode": "CNY", "currencyName": "Chinese Yuan" },
  { "country": "Colombia", "code": "CO", "currencyCode": "COP", "currencyName": "Colombian Peso" },
  { "country": "Comoros", "code": "KM", "currencyCode": "KMF", "currencyName": "Comorian Franc" },
  { "country": "Congo (Brazzaville)", "code": "CG", "currencyCode": "XAF", "currencyName": "Central African CFA Franc" },
  { "country": "Congo (Kinshasa)", "code": "CD", "currencyCode": "CDF", "currencyName": "Congolese Franc" },
  { "country": "Costa Rica", "code": "CR", "currencyCode": "CRC", "currencyName": "Costa Rican Colón" },
  { "country": "Croatia", "code": "HR", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Cuba", "code": "CU", "currencyCode": "CUP", "currencyName": "Cuban Peso" },
  { "country": "Cyprus", "code": "CY", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Czech Republic", "code": "CZ", "currencyCode": "CZK", "currencyName": "Czech Koruna" },
  { "country": "Denmark", "code": "DK", "currencyCode": "DKK", "currencyName": "Danish Krone" },
  { "country": "Djibouti", "code": "DJ", "currencyCode": "DJF", "currencyName": "Djiboutian Franc" },
  { "country": "Dominica", "code": "DM", "currencyCode": "XCD", "currencyName": "East Caribbean Dollar" },
  { "country": "Dominican Republic", "code": "DO", "currencyCode": "DOP", "currencyName": "Dominican Peso" },
  { "country": "Ecuador", "code": "EC", "currencyCode": "USD", "currencyName": "United States Dollar" },
  { "country": "Egypt", "code": "EG", "currencyCode": "EGP", "currencyName": "Egyptian Pound" },
  { "country": "El Salvador", "code": "SV", "currencyCode": "USD", "currencyName": "United States Dollar" },
  { "country": "Equatorial Guinea", "code": "GQ", "currencyCode": "XAF", "currencyName": "Central African CFA Franc" },
  { "country": "Eritrea", "code": "ER", "currencyCode": "ERN", "currencyName": "Eritrean Nakfa" },
  { "country": "Estonia", "code": "EE", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Eswatini", "code": "SZ", "currencyCode": "SZL", "currencyName": "Swazi Lilangeni" },
  { "country": "Ethiopia", "code": "ET", "currencyCode": "ETB", "currencyName": "Ethiopian Birr" },
  { "country": "Fiji", "code": "FJ", "currencyCode": "FJD", "currencyName": "Fijian Dollar" },
  { "country": "Finland", "code": "FI", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "France", "code": "FR", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Gabon", "code": "GA", "currencyCode": "XAF", "currencyName": "Central African CFA Franc" },
  { "country": "Gambia", "code": "GM", "currencyCode": "GMD", "currencyName": "Gambian Dalasi" },
  { "country": "Georgia", "code": "GE", "currencyCode": "GEL", "currencyName": "Georgian Lari" },
  { "country": "Germany", "code": "DE", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Ghana", "code": "GH", "currencyCode": "GHS", "currencyName": "Ghanaian Cedi" },
  { "country": "Greece", "code": "GR", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Grenada", "code": "GD", "currencyCode": "XCD", "currencyName": "East Caribbean Dollar" },
  { "country": "Guatemala", "code": "GT", "currencyCode": "GTQ", "currencyName": "Guatemalan Quetzal" },
  { "country": "Guinea", "code": "GN", "currencyCode": "GNF", "currencyName": "Guinean Franc" },
  { "country": "Guinea-Bissau", "code": "GW", "currencyCode": "XOF", "currencyName": "West African CFA Franc" },
  { "country": "Guyana", "code": "GY", "currencyCode": "GYD", "currencyName": "Guyanese Dollar" },
  { "country": "Haiti", "code": "HT", "currencyCode": "HTG", "currencyName": "Haitian Gourde" },
  { "country": "Honduras", "code": "HN", "currencyCode": "HNL", "currencyName": "Honduran Lempira" },
  { "country": "Hungary", "code": "HU", "currencyCode": "HUF", "currencyName": "Hungarian Forint" },
  { "country": "Iceland", "code": "IS", "currencyCode": "ISK", "currencyName": "Icelandic Króna" },
  { "country": "India", "code": "IN", "currencyCode": "INR", "currencyName": "Indian Rupee" },
  { "country": "Indonesia", "code": "ID", "currencyCode": "IDR", "currencyName": "Indonesian Rupiah" },
  { "country": "Iran", "code": "IR", "currencyCode": "IRR", "currencyName": "Iranian Rial" },
  { "country": "Iraq", "code": "IQ", "currencyCode": "IQD", "currencyName": "Iraqi Dinar" },
  { "country": "Ireland", "code": "IE", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Israel", "code": "IL", "currencyCode": "ILS", "currencyName": "Israeli New Shekel" },
  { "country": "Italy", "code": "IT", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Jamaica", "code": "JM", "currencyCode": "JMD", "currencyName": "Jamaican Dollar" },
  { "country": "Japan", "code": "JP", "currencyCode": "JPY", "currencyName": "Japanese Yen" },
  { "country": "Jordan", "code": "JO", "currencyCode": "JOD", "currencyName": "Jordanian Dinar" },
  { "country": "Kazakhstan", "code": "KZ", "currencyCode": "KZT", "currencyName": "Kazakhstani Tenge" },
  { "country": "Kenya", "code": "KE", "currencyCode": "KES", "currencyName": "Kenyan Shilling" },
  { "country": "Kiribati", "code": "KI", "currencyCode": "AUD", "currencyName": "Australian Dollar" },
  { "country": "Kuwait", "code": "KW", "currencyCode": "KWD", "currencyName": "Kuwaiti Dinar" },
  { "country": "Kyrgyzstan", "code": "KG", "currencyCode": "KGS", "currencyName": "Kyrgyzstani Som" },
  { "country": "Laos", "code": "LA", "currencyCode": "LAK", "currencyName": "Lao Kip" },
  { "country": "Latvia", "code": "LV", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Lebanon", "code": "LB", "currencyCode": "LBP", "currencyName": "Lebanese Pound" },
  { "country": "Lesotho", "code": "LS", "currencyCode": "LSL", "currencyName": "Lesotho Loti" },
  { "country": "Liberia", "code": "LR", "currencyCode": "LRD", "currencyName": "Liberian Dollar" },
  { "country": "Libya", "code": "LY", "currencyCode": "LYD", "currencyName": "Libyan Dinar" },
  { "country": "Liechtenstein", "code": "LI", "currencyCode": "CHF", "currencyName": "Swiss Franc" },
  { "country": "Lithuania", "code": "LT", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Luxembourg", "code": "LU", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Madagascar", "code": "MG", "currencyCode": "MGA", "currencyName": "Malagasy Ariary" },
  { "country": "Malawi", "code": "MW", "currencyCode": "MWK", "currencyName": "Malawian Kwacha" },
  { "country": "Malaysia", "code": "MY", "currencyCode": "MYR", "currencyName": "Malaysian Ringgit" },
  { "country": "Maldives", "code": "MV", "currencyCode": "MVR", "currencyName": "Maldivian Rufiyaa" },
  { "country": "Mali", "code": "ML", "currencyCode": "XOF", "currencyName": "West African CFA Franc" },
  { "country": "Malta", "code": "MT", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Marshall Islands", "code": "MH", "currencyCode": "USD", "currencyName": "United States Dollar" },
  { "country": "Mauritania", "code": "MR", "currencyCode": "MRU", "currencyName": "Mauritanian Ouguiya" },
  { "country": "Mauritius", "code": "MU", "currencyCode": "MUR", "currencyName": "Mauritian Rupee" },
  { "country": "Mexico", "code": "MX", "currencyCode": "MXN", "currencyName": "Mexican Peso" },
  { "country": "Micronesia", "code": "FM", "currencyCode": "USD", "currencyName": "United States Dollar" },
  { "country": "Moldova", "code": "MD", "currencyCode": "MDL", "currencyName": "Moldovan Leu" },
  { "country": "Monaco", "code": "MC", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Mongolia", "code": "MN", "currencyCode": "MNT", "currencyName": "Mongolian Tögrög" },
  { "country": "Montenegro", "code": "ME", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Morocco", "code": "MA", "currencyCode": "MAD", "currencyName": "Moroccan Dirham" },
  { "country": "Mozambique", "code": "MZ", "currencyCode": "MZN", "currencyName": "Mozambican Metical" },
  { "country": "Myanmar", "code": "MM", "currencyCode": "MMK", "currencyName": "Myanmar Kyat" },
  { "country": "Namibia", "code": "NA", "currencyCode": "NAD", "currencyName": "Namibian Dollar" },
  { "country": "Nauru", "code": "NR", "currencyCode": "AUD", "currencyName": "Australian Dollar" },
  { "country": "Nepal", "code": "NP", "currencyCode": "NPR", "currencyName": "Nepalese Rupee" },
  { "country": "Netherlands", "code": "NL", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "New Zealand", "code": "NZ", "currencyCode": "NZD", "currencyName": "New Zealand Dollar" },
  { "country": "Nicaragua", "code": "NI", "currencyCode": "NIO", "currencyName": "Nicaraguan Córdoba" },
  { "country": "Niger", "code": "NE", "currencyCode": "XOF", "currencyName": "West African CFA Franc" },
  { "country": "Nigeria", "code": "NG", "currencyCode": "NGN", "currencyName": "Nigerian Naira" },
  { "country": "North Korea", "code": "KP", "currencyCode": "KPW", "currencyName": "North Korean Won" },
  { "country": "North Macedonia", "code": "MK", "currencyCode": "MKD", "currencyName": "Macedonian Denar" },
  { "country": "Norway", "code": "NO", "currencyCode": "NOK", "currencyName": "Norwegian Krone" },
  { "country": "Oman", "code": "OM", "currencyCode": "OMR", "currencyName": "Omani Rial" },
  { "country": "Pakistan", "code": "PK", "currencyCode": "PKR", "currencyName": "Pakistani Rupee" },
  { "country": "Palau", "code": "PW", "currencyCode": "USD", "currencyName": "United States Dollar" },
  { "country": "Palestine", "code": "PS", "currencyCode": "ILS", "currencyName": "Israeli New Shekel" },
  { "country": "Panama", "code": "PA", "currencyCode": "PAB", "currencyName": "Panamanian Balboa" },
  { "country": "Papua New Guinea", "code": "PG", "currencyCode": "PGK", "currencyName": "Papua New Guinean Kina" },
  { "country": "Paraguay", "code": "PY", "currencyCode": "PYG", "currencyName": "Paraguayan Guaraní" },
  { "country": "Peru", "code": "PE", "currencyCode": "PEN", "currencyName": "Peruvian Sol" },
  { "country": "Philippines", "code": "PH", "currencyCode": "PHP", "currencyName": "Philippine Peso" },
  { "country": "Poland", "code": "PL", "currencyCode": "PLN", "currencyName": "Polish Złoty" },
  { "country": "Portugal", "code": "PT", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Qatar", "code": "QA", "currencyCode": "QAR", "currencyName": "Qatari Riyal" },
  { "country": "Romania", "code": "RO", "currencyCode": "RON", "currencyName": "Romanian Leu" },
  { "country": "Russia", "code": "RU", "currencyCode": "RUB", "currencyName": "Russian Ruble" },
  { "country": "Rwanda", "code": "RW", "currencyCode": "RWF", "currencyName": "Rwandan Franc" },
  { "country": "Saint Kitts and Nevis", "code": "KN", "currencyCode": "XCD", "currencyName": "East Caribbean Dollar" },
  { "country": "Saint Lucia", "code": "LC", "currencyCode": "XCD", "currencyName": "East Caribbean Dollar" },
  { "country": "Saint Vincent and the Grenadines", "code": "VC", "currencyCode": "XCD", "currencyName": "East Caribbean Dollar" },
  { "country": "Samoa", "code": "WS", "currencyCode": "WST", "currencyName": "Samoan Tālā" },
  { "country": "San Marino", "code": "SM", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Sao Tome and Principe", "code": "ST", "currencyCode": "STN", "currencyName": "São Tomé and Príncipe Dobra" },
  { "country": "Saudi Arabia", "code": "SA", "currencyCode": "SAR", "currencyName": "Saudi Riyal" },
  { "country": "Senegal", "code": "SN", "currencyCode": "XOF", "currencyName": "West African CFA Franc" },
  { "country": "Serbia", "code": "RS", "currencyCode": "RSD", "currencyName": "Serbian Dinar" },
  { "country": "Seychelles", "code": "SC", "currencyCode": "SCR", "currencyName": "Seychellois Rupee" },
  { "country": "Sierra Leone", "code": "SL", "currencyCode": "SLE", "currencyName": "Sierra Leonean Leone" },
  { "country": "Singapore", "code": "SG", "currencyCode": "SGD", "currencyName": "Singapore Dollar" },
  { "country": "Slovakia", "code": "SK", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Slovenia", "code": "SI", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Solomon Islands", "code": "SB", "currencyCode": "SBD", "currencyName": "Solomon Islands Dollar" },
  { "country": "Somalia", "code": "SO", "currencyCode": "SOS", "currencyName": "Somali Shilling" },
  { "country": "South Africa", "code": "ZA", "currencyCode": "ZAR", "currencyName": "South African Rand" },
  { "country": "South Korea", "code": "KR", "currencyCode": "KRW", "currencyName": "South Korean Won" },
  { "country": "South Sudan", "code": "SS", "currencyCode": "SSP", "currencyName": "South Sudanese Pound" },
  { "country": "Spain", "code": "ES", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Sri Lanka", "code": "LK", "currencyCode": "LKR", "currencyName": "Sri Lankan Rupee" },
  { "country": "Sudan", "code": "SD", "currencyCode": "SDG", "currencyName": "Sudanese Pound" },
  { "country": "Suriname", "code": "SR", "currencyCode": "SRD", "currencyName": "Surinamese Dollar" },
  { "country": "Sweden", "code": "SE", "currencyCode": "SEK", "currencyName": "Swedish Krona" },
  { "country": "Switzerland", "code": "CH", "currencyCode": "CHF", "currencyName": "Swiss Franc" },
  { "country": "Syria", "code": "SY", "currencyCode": "SYP", "currencyName": "Syrian Pound" },
  { "country": "Taiwan", "code": "TW", "currencyCode": "TWD", "currencyName": "New Taiwan Dollar" },
  { "country": "Tajikistan", "code": "TJ", "currencyCode": "TJS", "currencyName": "Tajikistani Somoni" },
  { "country": "Tanzania", "code": "TZ", "currencyCode": "TZS", "currencyName": "Tanzanian Shilling" },
  { "country": "Thailand", "code": "TH", "currencyCode": "THB", "currencyName": "Thai Baht" },
  { "country": "Timor-Leste", "code": "TL", "currencyCode": "USD", "currencyName": "United States Dollar" },
  { "country": "Togo", "code": "TG", "currencyCode": "XOF", "currencyName": "West African CFA Franc" },
  { "country": "Tonga", "code": "TO", "currencyCode": "TOP", "currencyName": "Tongan Paʻanga" },
  { "country": "Trinidad and Tobago", "code": "TT", "currencyCode": "TTD", "currencyName": "Trinidad and Tobago Dollar" },
  { "country": "Tunisia", "code": "TN", "currencyCode": "TND", "currencyName": "Tunisian Dinar" },
  { "country": "Turkey", "code": "TR", "currencyCode": "TRY", "currencyName": "Turkish Lira" },
  { "country": "Turkmenistan", "code": "TM", "currencyCode": "TMT", "currencyName": "Turkmenistan Manat" },
  { "country": "Tuvalu", "code": "TV", "currencyCode": "AUD", "currencyName": "Australian Dollar" },
  { "country": "Uganda", "code": "UG", "currencyCode": "UGX", "currencyName": "Ugandan Shilling" },
  { "country": "Ukraine", "code": "UA", "currencyCode": "UAH", "currencyName": "Ukrainian Hryvnia" },
  { "country": "United Arab Emirates", "code": "AE", "currencyCode": "AED", "currencyName": "United Arab Emirates Dirham" },
  { "country": "United Kingdom", "code": "GB", "currencyCode": "GBP", "currencyName": "British Pound Sterling" },
  { "country": "United States", "code": "US", "currencyCode": "USD", "currencyName": "United States Dollar" },
  { "country": "Uruguay", "code": "UY", "currencyCode": "UYU", "currencyName": "Uruguayan Peso" },
  { "country": "Uzbekistan", "code": "UZ", "currencyCode": "UZS", "currencyName": "Uzbekistani Soʻm" },
  { "country": "Vanuatu", "code": "VU", "currencyCode": "VUV", "currencyName": "Vanuatu Vatu" },
  { "country": "Vatican City", "code": "VA", "currencyCode": "EUR", "currencyName": "Euro" },
  { "country": "Venezuela", "code": "VE", "currencyCode": "VES", "currencyName": "Venezuelan Bolívar Soberano" },
  { "country": "Vietnam", "code": "VN", "currencyCode": "VND", "currencyName": "Vietnamese Đồng" },
  { "country": "Yemen", "code": "YE", "currencyCode": "YER", "currencyName": "Yemeni Rial" },
  { "country": "Zambia", "code": "ZM", "currencyCode": "ZMW", "currencyName": "Zambian Kwacha" },
  { "country": "Zimbabwe", "code": "ZW", "currencyCode": "ZWG", "currencyName": "Zimbabwe Gold" }
]